# Generated by Django 4.2.3 on 2023-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uploadimage_delete_demomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
